<?php

//Enqueue Vue
function get_vue() {
	wp_register_script( 'rest_api_vars', false );
	$rest_args = array(
		'rest_base' => site_url() . "/wp-json/core-vue/",
		'rest_nonce' => wp_create_nonce('wp_rest'),
	);
	wp_localize_script( 'rest_api_vars', 'nonce_object', $rest_args );
		
	if(is_admin()) return;
	
	$domain = site_url();
	$on_staging = strpos($domain, '.local');

	switch ($on_staging !== false) {
		case true:
			$app_root = "http://localhost:8080/js/";
			$app = "app.js";
			$chunks = "chunk-vendors.js";
			$css = "";
			break;
		
		case false:
			$app_root = site_url() . "/wp-content/themes/dagora-reports-shop/core/js/";
			$app = "app.1b72acf7.js";
			$chunks = "chunk-vendors.08d9be34.js";
			break;

		default:
			$app_root = site_url() . "/wp-content/themes/dagora-reports-shop/core/js/";
			$app = "app.1b72acf7.js";
			$chunks = "chunk-vendors.08d9be34.js";
			break;
	}

	wp_register_script( // the app build script generated by Webpack.
		'vue_app',
		$app_root . $app,
		array(),
		false,
		true
	); 
	wp_register_script( // the app build chunks script generated by Webpack.
		'vue_chunks',
		$app_root . $chunks,
		array(),
		false,
		true
	);

	// Single extra page scripts (only on staging)
	wp_register_script( // ABOUT PAGE
		'vue_app_about',
		$app_root . 'about.js',
		array(),
		false,
		true
	);
	wp_enqueue_script('vue_app_about');


	wp_enqueue_script('vue_app');
	wp_enqueue_script('vue_chunks');
	wp_enqueue_script( 'rest_api_vars' );

}
add_action('wp_enqueue_scripts', 'get_vue');
